CREATE TABLE CLIENTE (
ID_CLIENTE INT PRIMARY KEY NOT NULL IDENTITY(1,1),
NOME_CLIENTE VARCHAR(MAX) NOT NULL,
DATNAS_CLIENTE VARCHAR(MAX) NOT NULL,
CPF_CLIENTE VARCHAR(MAX) NOT NULL,
ENDERECO_CLIENTE VARCHAR(MAX) NOT NULL,
NUM_CLIENTE VARCHAR(MAX) NOT NULL,
BAIRRO_CLIENTE VARCHAR(MAX) NOT NULL,
CIDADE_CLIENTE VARCHAR(MAX) NOT NULL,
ESTADO_CLIENTE VARCHAR(MAX) NOT NULL,
TELEFONE_CLIENTE VARCHAR(MAX) NOT NULL,
EMAIL_CLIENTE VARCHAR(MAX) NOT NULL,
RG_CLIENTE VARCHAR(MAX) NOT NULL,
SEXO_CLIENTE VARCHAR(MAX) NOT NULL
)

CREATE TABLE FUNCIONARIOS (ID_FORNECEDOR INT PRIMARY KEY NOT NULL IDENTITY(1,1),
RAZSOCIAL_FORNECEDOR VARCHAR(MAX) NOT NULL,
NOMEFANT_FORNECEDOR VARCHAR(MAX) NOT NULL,
END_FORNECEDOR VARCHAR(MAX) NOT NULL,
BAIRRO_FORNECEDOR VARCHAR(MAX) NOT NULL,
CIDADE_FORNECEDOR VARCHAR(MAX) NOT NULL,
UF_FORNECEDOR VARCHAR(MAX) NOT NULL,
TEL_FORNECEDOR VARCHAR(MAX) NOT NULL,
EMAIL_FORNECEDOR VARCHAR(MAX) NOT NULL,
CPF_FORNECEDOR VARCHAR(MAX) NULL,
CNPJ_FORNECEDOR VARCHAR(MAX) NULL,
INSCRESTADUAL_FORNECEDOR VARCHAR(MAX) NOT NULL,
NUM_FORNECEDOR VARCHAR(MAX) NOT NULL
)

USE LOJA

SELECT * FROM CLIENTE